# Site settings
title: Building Responsive Data Visualization for the Web
email: bill@billhinderman.com
description: >
  With more than 1.4 billion smart phones and at least half as many tablets in use, there is a tremendous need for responsive web design in the data visualization sphere. Building Responsive Data Visualization for the Web answers the call for guidance with an authoritative and practical guide based on responsive web design principles.
baseurl: "" # the subpath of your site, e.g. /blog/
toc: "/chapters/" # TOC
url: "http://responsivedatavisualization.com" # the base hostname & protocol for your site
twitter_username: billhinderman
github_username:  billhinderman

# Build settings
markdown: kramdown

collections:
  chapters:
    output: true
  redirects:
    output: true
